# Generated by Django 5.1.2 on 2024-11-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
