# Generated by Django 5.1.2 on 2025-02-18 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reportmodel'),
        ('blogs', '0003_delete_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='reported_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_for_post', to='blogs.blogpost'),
        ),
    ]
