# Generated by Django 5.1.2 on 2025-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reportmodel_reported_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
