# Generated by Django 5.1.2 on 2025-02-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='banned',
            new_name='is_banned',
        ),
    ]
