# Generated by Django 5.0.7 on 2024-11-08 17:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post_liked', 'like_by')},
        ),
    ]
