# Generated by Django 5.1.2 on 2025-01-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogpost_status_alter_likes_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Views',
        ),
    ]
